"""empty message

Revision ID: 6fa7bda96305
Revises: 
Create Date: 2023-01-25 20:46:25.878903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa7bda96305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_cctv', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('permission')

    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.drop_column('brand_cctv')

    # ### end Alembic commands ###
